package ownExceptions;

public class MultipleByThreeException extends Exception{

}
